<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

  <xs:element name="VendorOrder">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Hdr">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="OrderId"  type="xs:string"/>
              <xs:element name="SoldTo"   type="xs:string"/>
              <xs:element name="Curr"     type="xs:string"/>
              <xs:element name="TotalAmt" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Itm" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Sku"       type="xs:string"/>
              <xs:element name="Qty"       type="xs:int"/>
              <xs:element name="UnitPrice" type="xs:decimal"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
